### ISSUE TITLE
Accordance with Azure SDK for Java Guidelines

### ISSUE THREAD

**Issue by brunoborges** [microsoft/credential-secure-storage-for-java#1]
Can the team please review the [Azure SDK Guidelines for Java Libraries](https://azure.github.io/azure-sdk/java_introduction.html), and identify what needs to be addressed to bring consistency with the other Azure SDKs already published on Maven Central?

// @jonathangiles

**Comment by JonathanGiles** [comment]
Agreed. I offered this support to @abyss638 earlier today - I want to be involved ASAP to get this into great shape before shipping.
